import "../../../globals.css";
import type { Metadata } from "next";
import Sidebar from "./sidebar/sidebar";
import { Inter } from "next/font/google";

const interSans = Inter({
  weight: "variable",
  variable: "--font-inter-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "cyber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.className} antialiased`}
      >
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
